# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

approxLogML <- function(muqBetaZero, sigsqqBeta0, muqgammaBeta, AqrhoBeta, BqrhoBeta, muqrecipSigsqBeta, muqbBeta, muqBetaTilde, SigmaqBetaTilde, muqrecipaBeta, lambdaqSigsqBeta, sBetaHYP, lambdaqaBeta, muqgammaU, AqrhoU, BqrhoU, muqrecipSigsqU, muqbU, muqUtilde, sigsqqUtilde, muqrecipaU, lambdaqSigsqU, sUHYP, lambdaqaU, muqrecipaEps, muqrecipSigsqEps, lambdaqaEps, lambdaqSigsqEps, sEpsHYP, n, ncZvec, familyNum, ySign, omega20) {
    .Call(`_gamselBayes_approxLogML`, muqBetaZero, sigsqqBeta0, muqgammaBeta, AqrhoBeta, BqrhoBeta, muqrecipSigsqBeta, muqbBeta, muqBetaTilde, SigmaqBetaTilde, muqrecipaBeta, lambdaqSigsqBeta, sBetaHYP, lambdaqaBeta, muqgammaU, AqrhoU, BqrhoU, muqrecipSigsqU, muqbU, muqUtilde, sigsqqUtilde, muqrecipaU, lambdaqSigsqU, sUHYP, lambdaqaU, muqrecipaEps, muqrecipSigsqEps, lambdaqaEps, lambdaqSigsqEps, sEpsHYP, n, ncZvec, familyNum, ySign, omega20)
}

drawInvGaussVec <- function(muVec) {
    .Call(`_gamselBayes_drawInvGaussVec`, muVec)
}

gamselBayesMCMCinner <- function(y, X, Z, familyNum, ncZvec, ncZmax, dGeneral, ZsttInds, ZendInds, XTy, XTX, ZTy, ZTX, ZTZ, sigmaBeta0HYP, sepsHYP, sbetaHYP, suHYP, AbetaHYP, BbetaHYP, AuHYP, BuHYP, numMCMC, msgCode) {
    .Call(`_gamselBayes_gamselBayesMCMCinner`, y, X, Z, familyNum, ncZvec, ncZmax, dGeneral, ZsttInds, ZendInds, XTy, XTX, ZTy, ZTX, ZTZ, sigmaBeta0HYP, sepsHYP, sbetaHYP, suHYP, AbetaHYP, BbetaHYP, AuHYP, BuHYP, numMCMC, msgCode)
}

gamselBayesMFVBinner <- function(y, X, Z, familyNum, ncZvec, ncZmax, dGeneral, ZsttInds, ZendInds, XTy, XTX, ZTy, ZTX, ZTZ, sigmaBeta0HYP, sEpsHYP, sBetaHYP, sUHYP, AbetaHYP, BbetaHYP, AuHYP, BuHYP, maxIter, toler, msgCode) {
    .Call(`_gamselBayes_gamselBayesMFVBinner`, y, X, Z, familyNum, ncZvec, ncZmax, dGeneral, ZsttInds, ZendInds, XTy, XTX, ZTy, ZTX, ZTZ, sigmaBeta0HYP, sEpsHYP, sBetaHYP, sUHYP, AbetaHYP, BbetaHYP, AuHYP, BuHYP, maxIter, toler, msgCode)
}

logPhi <- function(x) {
    .Call(`_gamselBayes_logPhi`, x)
}

omitMatCol <- function(A, j) {
    .Call(`_gamselBayes_omitMatCol`, A, j)
}

omitVecEnt <- function(a, j) {
    .Call(`_gamselBayes_omitVecEnt`, a, j)
}

printPercMsgs <- function(msgCode, loopSize, iLoop, percCnt) {
    .Call(`_gamselBayes_printPercMsgs`, msgCode, loopSize, iLoop, percCnt)
}

rTruncNormPos <- function(mu) {
    .Call(`_gamselBayes_rTruncNormPos`, mu)
}

zetad <- function(x) {
    .Call(`_gamselBayes_zetad`, x)
}

